##See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.
#
##Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
##For more information, please see https://aka.ms/containercompat
#
#FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
#WORKDIR /app
#EXPOSE 80
#EXPOSE 443
#
#FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
#WORKDIR /src
#COPY ["PlatformService/PlatformService.csproj", "PlatformService/"]
#RUN dotnet restore "PlatformService/PlatformService.csproj"
#COPY . .
#WORKDIR "/src/PlatformService"
#RUN dotnet build "PlatformService.csproj" -c Release -o /app/build
#
#FROM build AS publish
#RUN dotnet publish "PlatformService.csproj" -c Release -o /app/publish
#
#FROM base AS final
#WORKDIR /app
#COPY --from=publish /app/publish .
#ENTRYPOINT ["dotnet", "PlatformService.dll"]

#在教学视频的2:25:00处

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "PlatformService.dll" ]




#构建镜像文件命令：docker build -t xuehaq/platformservice .

#运行命令： docker run -p 8080:80 -d xuehaq/platformservice


#查看正在运行的容器： docker ps
#开始/停止运行： docker start/stop [id]


#docker push命令： docker push xuehaq/platformservice